name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: todopher-web

jobs:
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Create GitHub Release
        uses: actions/create-release@v1.1.4
        id: create_release
        with:
          tag_name: v${{ env.TAG }}
          release_name: "Release ${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          body: |
            ## 🏗 Deployment Instructions

            To run the application, **create a `.env` file** with the following content:
            ```txt
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=db
            DB_PORT=3306
            DB_NAME=${{ secrets.DB_NAME }}
            ```

            Then, start the services with:
            ```bash
            docker compose up --build
            ```

            The application will be available at `http://localhost:8080`.

            ### 🐳 **Pulling the image manually**
            ```bash
            docker pull ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ```

            ### 🛠 **Running the database manually**
            ```bash
            docker run -d --name todopher-db -e MYSQL_ROOT_PASSWORD=${{ secrets.DB_PASSWORD }} -p 3306:3306 mysql:8.0
            ```

            ### 🚀 **Running the app manually**
            ```bash
            docker run -p 8080:8080 --env-file .env ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ```

            🔥 **Docker image is available in the GitHub Container Registry.**
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
