name: Format Go Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: Run gofmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run gofmt
        run: |
          files=$(gofmt -l .)
          if [ -n "$files" ]; then
            echo "Go files not formatted:" $files
            exit 1
          fi
