name: Build and Release

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: todopher-web

jobs:
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Create GitHub Release
        uses: actions/create-release@v1.1.4
        id: create_release
        with:
          tag_name: v${{ env.TAG }}
          release_name: "Release ${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          body: |
            ### 🏗 Deployment Instructions

            To start the application:
            1. Download the source code from the assets.
            2. Unzip the folder.
            3. Go to the root directory(todopher-web) and run the following command:
            ```bash
            docker compose up --build
            ```

            The application will be available at `http://localhost:8080`.

            Otherwise, you can run the application manually:

            ### **Pull the image**
            ```bash
            docker pull ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ```

            ### **Create a docker network**
            ```bash
            docker network create todopher-network
            ```

            ###  **Run the database**
            ```bash
            docker run -d --name db --network todopher-network -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=tododb -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -p 3306:3306 mysql:8.0
            ```

            ###  **Run the app**
            ```bash
            docker run -d --name todopher-web --network todopher-network -p 8080:8080 ghcr.io/nendix/todopher-web/todopher-web:20250206202312
            ```

             **Docker image is available in the GitHub Container Registry.**
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
